version: '3'

services:

  virtualmuseum_visualization:
    container_name: virtualmuseum_visualization
    build: ./virtual_museum_visualization
    ports:
      - "1234:80" # remember the port expose syntax is HOST:CONTAINER !!! DO NOT CHANGE CONTAINER's  port value (port 80). You may only change the port in which the host can access the web service
    depends_on:
      - persistence_layer
    volumes:
      - ./virtual_museum_visualization:/app/
    networks:
      - museum
    environment:
      - MONGO_CONNECT=mongodb://persistence_layer:27017
      - PYTHONUNBUFFERED=True
  
  persistence_layer:
    image: "mongo:4.2.2"
    container_name: persistence_layer
    ports: 
      - "27017:27017"
    volumes:
      - persistence_layer:/data/db
    networks:
      - museum

  virtualmuseum_manager:
    container_name: virtualmuseum_manager
    build: ./virtual_museum_manager
    ports:
      - "1331:8521"
    depends_on:
      - persistence_layer
    volumes:
      - ./virtual_museum_manager:/mesa/
    networks:
      - museum
    environment:
      - MONGO_CONNECT=mongodb://persistence_layer:27017
      - open_2d_canvas=False
      - autoreload=False
      - PYTHONUNBUFFERED=True
  
  
networks:
  museum:
    driver: bridge

volumes:
  persistence_layer:
      


   

 
